### ISSUE TITLE
屏幕分享黑屏

### ISSUE THREAD

**Issue by zdq1179169386** [pili-engineering/QNRTC-iOS#16]
两个都是iOS 12的手机，其中一个选择的是屏幕分享，另一个看到的是黑屏，无法看到手机屏幕，demo 和 App Store 上的都试过了

**Comment by suweiz19890921** [comment]
屏幕分享功能就没有实现！都没有看到添加 extention

**Comment by Kivenhaoyu** [comment]
app 内部屏幕分享已实现，具体可查看对应的文档
