### ISSUE TITLE
在发起通话接入通话前，播放自定义音频冲突问题

### ISSUE THREAD

**Issue by charlesYun** [pili-engineering/QNRTC-iOS#27]
通过AVAudioPlayer在发起通话加入房间前播放自定义音频，冲突问题。主要现象就是播放的时候卡顿一下

**Comment by Kivenhaoyu** [comment]
因为 iOS 调用音频相关操作，一定会涉及共同使用的系统底层设置，如果需要使用 AVAudioSession 等底层共同设置，需要统一设置和控制，具体的问题需要整体控制底层调用
