### ISSUE TITLE
最新ios2.3.1版本兼容其他音频播放问题

### ISSUE THREAD

**Issue by charlesYun** [pili-engineering/QNRTC-iOS#30]
我遇到的问题是，我发起了通话，后端给我了token，我先加入了房间，发布了本地的音视频track, 然后等待订阅远端用户成功的回调，在这期间，我会通过系统的AVAudioPlayer 来播放 一个呼叫中的音频，但是会出现那种播放被中断 一下的情况，我试过设置AVAudioSessionModeVoiceChat 或者 AVAudioSessionModeVideoChat 都无效。

**Comment by Kivenhaoyu** [comment]
当前 sdk 在使用本地音频时必须使用 AVAudioSession ，这个是 iOS 共同使用的系统底层设置，如果需要使用 AVAudioSession 等底层共同设置，需要统一设置，目前不支持在 sdk 音频通过化过程中更改 AVAudioSession 等系统操作
