### ISSUE TITLE
接收方听不到声音

### ISSUE THREAD

**Issue by f458217257** [pili-engineering/QNRTC-iOS#39]
先让a,b加入同一个房间,a切换到微信打语音电话后,切回到软件。b在a拨打语音电话之后就听不到a的声音了。

**Comment by Kivenhaoyu** [comment]
麻烦尽可能详细的信息，如下：
1 具体测试机型以及版本
2 是否毕现
3 appid roomname userid 以及对应触发时间点
等上述信息
