### ISSUE TITLE
插拔耳机后声音异常

### ISSUE THREAD

**Issue by f458217257** [pili-engineering/QNRTC-iOS#40]
1.a和b加入房间，a在聊天的过程中插拔耳机，b那边出现电流音，回声。
2.a和b加入房间，a在聊天过程中来电话了，把电话挂了之后，a和b的听筒有杂音

**Comment by Kivenhaoyu** [comment]
麻烦尽可能详细的信息，如下：
1 具体测试机型以及版本
2 是否毕现
3 appid roomname userid 以及对应触发时间点
等上述信息
