### ISSUE TITLE
房间状态回调（roomStateDidChange）由connecting变为idle

### ISSUE THREAD

**Issue by zhang-Kai-Jun** [pili-engineering/QNRTC-iOS#41]
self.engine.joinRoom后，房间状态回调由connecting 变为 idle，请问这个是因为什么呢？

**Comment by Kivenhaoyu** [comment]
你好，当前变更是因为房间连接出错，无法重连，可以查看一下  didFailWithError 的错误回调，或者尽可能提供一下对应的 appid、 roomname 、userid 等信息
