### ISSUE TITLE
SDK内包含过期类UIWebView

### ISSUE THREAD

**Issue by DaBinGe** [pili-engineering/QNRTC-iOS#44]
% grep -r UIWebView .
Binary file ./Pods/QNRTCKit/Pod/iphoneos/QNRTCKit.framework.dSYM/Contents/Resources/DWARF/QNRTCKit matches
苹果打包上传，不给上传包含UIWebView的代码

**Comment by DaBinGe** [comment]
版本号是：pod 'QNRTCKit',       '3.0.2'

**Comment by Kivenhaoyu** [comment]
当前版本并未涉及任何 UIWebView 代码，对于对应的 dSYM 可以直接删除，并不影响对应的功能发布
